name: Remove old tags

on:
  push:
    branches:
      - '**'

jobs:
  update_tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List existing tags
        run: |
          git fetch --prune --tags
          EXISTING_TAGS=$(git tag --sort=-v:refname)
          echo "EXISTING_TAGS=$EXISTING_TAGS" >> $GITHUB_ENV
          echo "Existing tags: $EXISTING_TAGS"

      - name: Delete old tags
        run: |
          MAX_TAGS=10  # Número máximo de tags
          TAGS_TO_DELETE=$(echo "$EXISTING_TAGS" | tail -n +$((MAX_TAGS + 1)))
          echo "TAGS_TO_DELETE=$TAGS_TO_DELETE" >> $GITHUB_ENV
          echo "Tags to delete: $TAGS_TO_DELETE"
          for TAG in $TAGS_TO_DELETE; do
            git tag -d $TAG
          done

      - name: Delete old tags (remote)
        run: |
          for TAG in $TAGS_TO_DELETE; do
            git push --delete origin $TAG
          done