name: Remove old tags

on:
  push:
    branches:
      - '**'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verificar número de tags
        id: tags
        # echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
        run: |
          tags_count=$(git tag --sort=-creatordate | wc -l)
          echo "tag_count=$tags_count" >> $GITHUB_OUTPUT

      - name: Limpar Tags Antigas
        if: ${{ steps.tags.outputs.tag_count > 10 }}
        run: |
          git tag --sort=-creatordate | tail -n +11 | xargs -I{} git push --delete origin {}