name: Update tag on merge

on:
  pull_request:
    types: [closed]

jobs:
  update_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
          # if you unshallow in a separate step, use the following option:
          # skip-unshallow: 'true'
          
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
      
      - name: Get current tag
        run: echo ::set-env name=TAG::$(git describe --abbrev=0 --tags)

      - name: Update tag version
        run: ./update_tag.sh ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
