name: Update tag on merge

on:
  pull_request:
    types: closed
    branches:
      - development
      - main

jobs:
  update_tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: PR merged in main
        if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: ""
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
        

      - name: PR merged in development
        if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development' }}
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: ""
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}-RC.${increment}"
        
      - name: Create version tag
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          git config --local user.email "stany@collection.com.br"
          git config --local user.name "Collec_CICD"
          git tag -a ${{ steps.semantic.outputs.version }} -m "New Version from ${{ github.event.pull_request.head.ref }}: ${{ steps.semantic.outputs.version }}"
          git push origin ${{ steps.semantic.outputs.version }}