name: Update tag on merge

on:
  pull_request:
    types: [closed]

jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

  update_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Get current tag
        run: echo ::set-env name=TAG::$(git describe --abbrev=0 --tags)

      - name: Update tag version
        run: ./update_tag.sh ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
